---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: mnist-hyperparameter-tuning
  namespace: kubeflow
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
  algorithm:
    algorithmName: random
  parallelTrialCount: 3
  maxTrialCount: 9
  maxFailedTrialCount: 3
  parameters:
    - name: --lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.1"
    - name: --batch_size
      parameterType: categorical
      feasibleSpace:
        list:
          - "32"
          - "64"
          - "128"
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: lr
        description: Learning rate
        reference: --lr
      - name: batch_size
        description: Batch size
        reference: --batch_size
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: fsgurapsl/mnist-trainer:latest
                command:
                  - "python"
                  - "/app/train.py"
                  - "--lr=${trialParameters.lr}"
                  - "--batch_size=${trialParameters.batch_size}"
                resources:
                  limits:
                    cpu: "1"
                    memory: "1Gi"
            restartPolicy: Never
